name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: create build directory
      run: mkdir build
    - name: cmake
      run: cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: make
      run: cd build && make
    - name: test
      run: cd build && ./test/unit_tests
